### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by Andrew-peng** [fmnisme/python-icinga2api#9]
When I try to `pip install python-icinga2api` I run into this issue

```
Collecting python-icinga2api
  Downloading python-icinga2api-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f2/gbq70grs27b489_p38tcny09r9xfww/T/pip-build-_KNCed/python-icinga2api/setup.py", line 25, in <module>
        long_description=read('README.md'),
      File "/private/var/folders/f2/gbq70grs27b489_p38tcny09r9xfww/T/pip-build-_KNCed/python-icinga2api/setup.py", line 13, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/f2/gbq70grs27b489_p38tcny09r9xfww/T/pip-build-_KNCed/python-icinga2api/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/f2/gbq70grs27b489_p38tcny09r9xfww/T/pip-build-_KNCed/python-icinga2api/
```

I am using pip version 9.0.1 on python 2.7. Looks like a packaging issue

**Comment by daleki** [comment]
Looks like it is related to: 
https://github.com/fmnisme/python-icinga2api/blob/master/setup.py#L21

Commit:  https://github.com/fmnisme/python-icinga2api/commit/7ab55f1a095430cbb3bb5406029819390f08202f

**Comment by colorchestra** [comment]
I just had the same problem, using pip 9.0.1 on a freshly installed Raspbian Stretch system. I worked around it though by doing `pip3 download python-icinga2api`, unpacking it and removing the line referenced by @daleki from setup.py. A `README.md` is definitely not present.
